### ISSUE TITLE
Potential Leak of sensitive information

### ISSUE THREAD

**Issue by timsankara** [mchemweno/Backend#2]
**Should this information really be public?**

businessShortCode = "174379"  # lipa na mpesa shortcode
phone_no = 254726990002
lipa_na_mpesa_passkey = "bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919"
consumer_key = "kAo0oAnDLPbYfyGr7iAtMNA5ELxyFe9G"
consumer_secret = "SGtdEOY52ZA71FD5"
shortcode = "600119"
test_msisdn = 254708374149
lipa_na_mpesa_online_callback_url = "https://pacific-castle-77566.herokuapp.com/api/payments/lnm/"
lipa_na_mpesa_online_transaction_description = "Tithe"

mpesa_c2b_confirmation_url = "https://pacific-castle-77566.herokuapp.com/api/payments/c2b_confirmation/"

mpesa_c2b_validation_url = "https://pacific-castle-77566.herokuapp.com/api/payments/c2b_validation/"

**Comment by mchemweno** [comment]
Test credentials..... Lol

**Comment by mchemweno** [comment]
Will pull it down though

**Comment by timsankara** [comment]
> Test credentials..... Lol

Hehe no pressure....
